blank_issues_enabled: false
contact_links:
  - name: Questions and show & tell
    url: https://github.com/bjakapong416/imgen9/discussions
    about: Ask how to do something, or share the characters you made.
